### ISSUE TITLE
Remove multiline commit messages from activity.md

### ISSUE THREAD

**Issue by StoneyJackson** [StoneyJackson/git-ccscne-2016#2]

**Comment by burdged** [comment]
I decided to leave this. I modified it so that it was more obvious that it was a comment. I had students who were trying to type the comment in. I also included what they needed to type in order to save and quit. Does this instruction work for you as well?

**Comment by StoneyJackson** [comment]
Are we talking about in Section E, the text in the textbox:

# This will open the vim editor; write a multi-line commit 
# message, save and quit (press esc and then type :wq!).

If so, I'm fine with this solution.
