### ISSUE TITLE
Terminal startup instructions

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/git-ccscne-2016#6]
You need to include the instructions for starting up the terminal in Mac OSX and Linux.

**Comment by StoneyJackson** [comment]
I think we can skip directions for Linux. If they are using Linux, they probably know how to open a terminal. It would be difficult to use Linux without ever having to use the terminal. Also, how one opens a terminal on Linux depends on the window manager they are using (kde, gnome, etc.). If someone is stuck, we'll have to try to help them individually.

For OS X: Finder -> Applications -> Utilities -> Terminal.app
